Partial Commit

diff --git a/db b/db
--- a/db
+++ b/db
@@ -1,9 +1,39 @@
 #!/bin/bash
 
-if [[ $(pwd) == "$HOME/cppcp" ]]; then
-    name=$(cat .stor/source.txt)
-    if [[ ! -f .exec/${name}.out ]]; then
-		clang++ -g -fno-omit-frame-pointer -include-pch libraries/bits/stdc++.h "${name}.cpp" -std=c++20 -Wno-vla -o ".exec/${name}.out"
-    fi
-	lldb -o "settings set target.input-path .stor/inp0.txt" ".exec/${name}.out"
+if [[ $(pwd) != "$HOME/cppcp" ]]; then
+	echo "Run from $HOME/cppcp"
+	exit 1
 fi
+tempdir=.tmp/
+sourcepath=${tempdir}source.txt
+usage="
+Usage:
+        $(basename $0)
+
+Description:
+        Runs lldb on $sourcepath with input set to ${tempdir}inp0.txt
+"
+if [[ $# -ne 0 ]]; then
+	echo "No arguments expected."
+	echo "$usage"
+	exit 1
+fi
+if [[ ! -f $sourcepath ]]; then
+	echo "$sourcepath not found."
+	exit 1
+fi
+
+name=$(<$sourcepath)
+if [[ ! -f ${tempdir}${name}.out ]]; then
+	if [[ ! -f "${name}.cpp" ]]; then
+		echo "Latest ed-modified file '${name}.cpp' missing."
+		exit 1
+	fi
+	. config/compile.sh
+fi
+if [[ ! -f ${tempdir}inp0.txt ]]; then
+	echo "No program input file '${tempdir}inp0.txt'."
+	exit 1
+fi
+. config/debug.sh
+
